name: Deploy Dist folder

on:
  push:
    branches:
      - main
      - "feature/**"
    paths-ignore:
      - README.md
      # - ".github/workflows/*"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v5

      - name: Setup Node.js and install dependencies
        uses: ./.github/actions/setup_node
        with:
          node-version: 22
      - name: Run test
        run: npm run test
  build:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v5
      - name: Setup Node.js and install dependencies
        uses: ./.github/actions/setup_node

      - name: Build project
        run: npm run build
      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: dist-folder
          path: dist
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download dist folder
        uses: actions/download-artifact@v4
        with:
          name: dist-folder
          path: dist
      - name: deploy dist folder
        run: |
          echo "Deploying dist folder..."
          ls dist
          echo "Complete!"
