name: Deploy Dist folder

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        run: |
          echo "Fetching latest code from main branch"
          git clone  https://github.com/yulian911/my-portfolio.git myfiles
          cd myfiles && ls -la
