name: CD/CI Pipeline

on: push

jobs:
  greetings:
    runs-on: ubuntu-latest

    steps:
      - name: Greet user
        runs: echo "Hello World"
      - name: Bye user
        runs: echo "Goodbye World"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
